name: hn_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  url_launcher: any
  built_value: ^7.0.0
  built_collection: ^4.3.0
  http: ^0.12.0+2
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  built_value_generator: ^7.0.0
  build_runner: ^1.7.2




flutter:


  uses-material-design: true

  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf
        - asset: fonts/EBGaramond-Italic.ttf
          style: italic
        - asset: fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: fonts/EBGaramond-BoldItalic.ttf
          weight: 700
          style: italic

